language: php

php:
  - 5.5
  - 5.4
  - 5.3
  
before_install:
  - pecl install pthreads-beta
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash
  
script:
  - ant build

notifications:
  email: info@appserver.io
  hipchat: 95d47a72c5372d4a0fef20048c3200@Appserver